# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - cinefds

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd CineFds/
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm ci
          cd ..

      - name: Run local server
        run: |
          cd CineFds/
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          npx cypress run

      - name: Cleaning testing files
        run: |
          cd CineFds/
          rm .env
          rm db.sqlite3
          rm cypress.config.js
          rm package-lock.json
          rm package.json
          rm -rf cypress
          rm -rf node_modules
          cd ..


      - name: Zip artifact for deployment
        run: |
          cd CineFds/
          zip release.zip ./* -r
          cd ..
          mv CineFds/release.zip .
        
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_889BD2EE1F774EF2A68C2E2ADC1628C8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F8EEA79ABADE4A968961BD12921E00C8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3C22DC8E5B204F4D8CFAF66CAEF0CEA6 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'cinefds'
          slot-name: 'Production'
          
