# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Test python app - cinefds

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd CineFds/
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm ci
          cd ..

      - name: Run local server
        run: |
          cd CineFds/
          python manage.py migrate
          python manage.py runserver &
          sleep 5
          npx cypress run

      - name: Cleaning testing files
        run: |
          cd CineFds/
          rm .env
          rm db.sqlite3
          rm cypress.config.js
          rm package-lock.json
          rm package.json
          rm -rf cypress
          rm -rf node_modules
          cd ..

          
